baseURL: "https://moijosan.com/"
title: Moijosan
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Moises Sanchez
  description: "Personal site for Moises Sanchez"
  keywords: [Blog, Portfolio, Linux, PaperMod, Software Engineering, Web Development, Game Development, Central Coast]
  author: Moises Sanchez
  images: ["<link or path of image for opengraph, twitter-cards>"]
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: 
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  profileMode:
      enabled: true
      title: "Oh-Hay"
      subtitle: "Just a digital sea-critter that likes building things."
  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/moisesjsanchez/"
    - name: github
      url: "https://github.com/themolluskdev"

menu:
  main:
    - identifier: about
      name: WhoAmI 👋🏾
      url: /About/
      weight: 4
    - identifier: projects
      name: Cool Stuff ✨
      url: /projects/
      weight: 2
    - identifier: blog
      name: Blog Stuff  📚
      url: /blog/
      weight: 2